---
- hosts: localhost
  tasks:
    - name: Install the requirements 
      shell: ansible-galaxy install -r requirements.yml
    - name: Install homebrew
      include_role:
        name: geerlingguy.homebrew
    - name: "add custom homebrew repos"
      community.general.homebrew_tap:
        name:
          [
            adoptopenjdk/openjdk,
            cavaliercoder/dmidecode,
            fishtown-analytics/dbt,
            homebrew/cask-versions,
            thoughtbot/formulae,
            weaveworks/tap,
            datawire/blackbird,
            hashicorp/tap,
            homebrew/bundle,
            homebrew/core,
            microsoft/mssql-release,
            mongodb/brew,
            warrensbox/tap,
          ]
    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - whatsapp
        - lastpass
        - adoptopenjdk/openjdk/adoptopenjdk8
        - dash # documentation lookup
        - datagrip
        - docker
        # - hicolor-icon-theme
        #- dmidecode
        - google-chrome
        - google-cloud-sdk
        - ngrok # create localhost public through public server
        #- osxfuse # enable ntfs windows support
        # - postico # connecting to postgres
        - postman
        # - rstudio
        - slack
        - signal
        - tunnelblick
        - virtualbox
        - visual-studio-code
        #watchman
    - name: "Install homebrew packages"
      ignore_errors: yes
      community.general.homebrew:
        name: [
	          "wget",
            "unzip",
            "ca-certificates",
            "autoconf",
            "automake",
            "aws-iam-authenticator",
            "awscli",
            "rename",
            "azure-cli",
            "ansible",
            "awslogs",
            "bash-git-prompt",
            "kubernetes-cli",
            "kubernetes-helm",
            "go",
            "tree",
            "tfswitch",
            #"mssql-tools",
            "mongodb-database-tools",
            "minikube",
            "tflint",
            "terragrunt",
            "terraform_landscape",
            "gpg",
            # 'dnsmasq#'
            "direnv",
            "python",
            "iproute2mac",
          ]
        state: present
        update_homebrew: yes
    - block:
        - name: Get the path to ZSH
          become: false
          local_action: command which zsh
          register: zsh_path

        - name: "Ensure homebrew zsh is in allowed shells"
          lineinfile:
            path: /etc/shells
            line: "{{ zsh_path.stdout }}"
        - name: Install Oh My ZSH
          shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
          args:
            creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

        - name: Install iStat Menus
          shell: wget -O istat.zip https://download.bjango.com/istatmenus/
          
        - name: Click Install on the popup MANUALLY
          shell: unzip istat && cd iStat*/Contents/MacOS/ && ./iStat*
          
        - name: Download Hyper
          shell: wget -O Hyper.dmg https://releases.hyper.is/download/mac
        - name: Move Hyper in the Apps
          shell: hdiutil attach Hyper.dmg && cp -R /Volumes/Hyper*/Hyper.app  /Applications
        - name: Set ZSH as the default shell
          shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
        - name: "Create a default ZSH configuration"
          template:
            src: templates/.zshrc.j2
            dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
            owner: "{{ lookup('env', 'USER') }}"
            force: yes
      become: yes 
      ignore_errors: yes
